package com.thishood.domain

import com.thishood.UUIDGenerator

/**
 * Signup (aka registration) data.
 * Also generated by application when block lead 'invites' neighbors. See {@link SignupInvitation#status} for workflow
 *
 */
class SignupInvitation {
	String token = UUIDGenerator.next()
	/**
	 * Will be set only when invitation was performed and email conforms rfc with personal data
	 */
	String personal
	String email
	/**
	 * auto-assignment to block
	 */
	Hood hood
	/**
	 * To distinguish invites from registrations
	 */
	Boolean invitedPersonally = false
	SignupInvitationStatus status

	Date dateCreated

	static constraints = {
		token nullable: false
		personal nullable: true
		email nullable: false, email: true
		hood nullable: true
	}
}
