recaptcha {

	// Set to false to disable the display of captcha
	enabled = true

	// Communicate using HTTPS
	useSecureAPI = true

	// These keys are generated by the ReCaptcha service

	// Include the noscript tags in the generated captcha
	includeNoScript = true
}

mailhide {
    // Generated by the Mailhide service
    publicKey = ""
    privateKey = ""
}

environments {
  development {
    recaptcha {
      // Communicate using HTTPS
      useSecureAPI = false

	publicKey = "6LdpSsQSAAAAAE1P78FpGWV1SirwwUd8PM6OZCMY"
	privateKey = "6LdpSsQSAAAAAAREth7L1A6iq88pu7_goxTI9Rhm"
    }
  }
  test {
    recaptcha {
	publicKey = "6LdhSsQSAAAAAHE88i2jlEkeQMnEscoMgG9ITs-9"
	privateKey = "6LdhSsQSAAAAABdPwuy5D4ILaUItkS4u-RuLP_Yd"

    }
  }
  production {
    recaptcha {
	publicKey = "6LdgSsQSAAAAALkrAGywOJl08bhqESlIYJC1N8uY"
	privateKey = "6LdgSsQSAAAAAHVr5QXOSolBgZUsx71qVyMYu9bo"

    }
  }
}